import { styleSheetFactory } from "../../constants/Theme";
import { Colors } from "../../constants/types";

export const styles = styleSheetFactory((theme: Colors) => ({
  column: {
    flexDirection: "column",
    alignSelf: "stretch",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    alignSelf: "stretch",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    alignSelf: "stretch",
    marginBottom: 24,
  },
  modal: {
    borderWidth: 0,
    borderColor: "transparent",
    alignSelf: "stretch",
  },
  background: {
    backgroundColor: "#00000090",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
  },
  modalView: {
    backgroundColor: theme.background,
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    paddingHorizontal: 28,
    paddingBottom: 24,
    paddingTop: 20,
    justifyContent: "space-around",
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
  },
  titleText: {
    fontWeight: "bold",
    fontSize: 18,
    color: theme.titleText,
    paddingTop: 8,
    alignSelf: "stretch",
    textAlign: "center",
  },
  input: {
    height: 40,
    marginVertical: 8,
    padding: 4,
    paddingLeft: 8,
    borderWidth: 1,
    borderColor: theme.border,
    color: theme.text,
    alignSelf: "stretch",
    width: "40%",
    borderRadius: 50,
  },
  commandText: {
    color: theme.text,
    minWidth: "55%",
    marginRight: 8,
  },
  buttonText: {
    color: theme.buttonText,
    fontWeight: "bold",
    fontSize: 18,
    textAlign: "center",
  },
  button: {
    borderRadius: 50,
    marginVertical: 8,
    flex: 1,
    overflow: "hidden",
  },
  gradientButton: {
    padding: 8,
  },
  icon: {
    color: "#52554F",
  },
  imageUpload: {
    backgroundColor: "#f2f2f2",
    width: 150,
    height: 150,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    marginBottom: 8,
  },
  uploadColumn: {
    flexDirection: "column",
    alignSelf: "stretch",
    justifyContent: "center",
    marginLeft: 8,
    marginBottom: 8,
    width: 150,
  },
  uploadButton: {
    borderColor: theme.border,
    borderWidth: 1,
    borderRadius: 8,
    marginVertical: 8,
    padding: 4,
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  uploadText: {
    color: theme.text,
  },
  uploadButtonText: {
    color: theme.text,
  },
  areaContainer: {
    height: 100,
    borderRadius: 16,
  },
}));
